global:
  scrape_interval: 2s
  evaluation_interval: 2s

scrape_configs:
  - job_name: 'apiGateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:9000']
  - job_name: 'springMongo'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080'] ## only for demo purposes don't use host.docker.internal in production
        labels:
          application: "springMongo"
  - job_name: 'orderService'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8081'] ## only for demo purposes don't use host.docker.internal in production
        labels:
          application: 'Order Service'
  - job_name: 'Inventory'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal.8082']
        labels:
          application: 'Inventory Service'
  - job_name: 'notificationService'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8083']
        labels:
          application: 'Notification Service'



